### ISSUE TITLE
vsfsm.c

### ISSUE THREAD

**Issue by hongshui3000** [vsfteam/vsf#1]
fsm framework 这个不打算再支持了？

**Comment by versaloon** [comment]
不好意思，刚刚看到这个邮件，新版本里，使用vsf_eda实现同样功能。

--------------原始邮件--------------
发件人："yxh "<notifications@github.com>;
发送时间：2019年8月23日(星期五) 下午3:46
收件人："vsfteam/vsf" <vsf@noreply.github.com>;
抄送："Subscribed "<subscribed@noreply.github.com>;
主题：[vsfteam/vsf] vsfsm.c (#1)
-----------------------------------

 
这个不打算再支持了？

**Comment by hongshui3000** [comment]
感谢回复，再问下  ：eda 是什么缩写？

**Comment by GorgonMeducer** [comment]
Event-Driven-Architecture
