### ISSUE TITLE
multiplex_spi.c编译警告修复

### ISSUE THREAD

**Issue by versaloon** [vsfteam/vsf#128]
VC下，llvm编译器：

1>..\..\vsf\source\hal\driver\common\spi\multiplex_spi.c(364,10): warning : unused variable 'is_hardware' [-Wunused-variable]
1>..\..\vsf\source\hal\driver\common\spi\multiplex_spi.c(437,9): warning : variable 'result' is used uninitialized whenever 'if' condition is false [-Wsometimes-uninitialized]
1>..\..\vsf\source\hal\driver\common\spi\multiplex_spi.c(445,12): message : uninitialized use occurs here
1>..\..\vsf\source\hal\driver\common\spi\multiplex_spi.c(437,5): message : remove the 'if' if its condition is always true
1>..\..\vsf\source\hal\driver\common\spi\multiplex_spi.c(435,5): message : variable 'result' is declared here
1>..\..\vsf\source\hal\driver\common\spi\multiplex_spi.c(475,18): warning : unused variable 'result' [-Wunused-variable]

**Comment by liangyongxiang** [comment]
除了警告，还有和i2c类似的保护问题。后面修复。

**Comment by liangyongxiang** [comment]
中断保护问题，在这里跟踪：https://github.com/vsfteam/vsf/issues/136
