### ISSUE TITLE
请问vsf支持装载运行elf吗？

### ISSUE THREAD

**Issue by juiceRv** [vsfteam/vsf#7]
请问vsf支持装载运行elf吗？谢谢

**Comment by versaloon** [comment]
@juiceRv 目前没做这个支持，不过技术上并没有瓶颈

**Comment by juiceRv** [comment]
好的，感谢大佬的回复。

**Comment by versaloon** [comment]
elf已经支持，后面等客户验证之后，会准备文档
不过，elf目前基本都是配合linux子系统使用
一些GPL的代码，可以独立编译成elf，动态加载运行
