### ISSUE TITLE
vsf json

### ISSUE THREAD

**Issue by Shin-ing** [vsfteam/vsf#75]
vsf_json_get_number, 应该删掉引号判断代码
    if (*json++ != '"') {
        return -1;
    }
考虑添加isdigit，判断

**Comment by versaloon** [comment]
多谢，我看了一下json格式，number确实不需要引号。
不过vsf里的joson库基本没人用，所以也没发现这个问题。

**Comment by Shin-ing** [comment]
省空间，瞅了一眼，评估一下大小

**Comment by versaloon** [comment]
vsf_json_set_integer也需要做类似的修改。
这个设计就是为了最精简，不需要中间结构体，不依赖heap，不过是牺牲性能换取的。

**Comment by versaloon** [comment]
vsf_json_set_integer没问题，vsf_json_get_number已经修复了。多谢
