### ISSUE TITLE
Example CMake Error

### ISSUE THREAD

**Issue by leeebo** [vsfteam/vsf#8]
您好，感谢您贡献的 vsf。我在尝试编译 `vsf/example/template/project/cmake/esp32s2` 示例工程时，出现了多处 CMake Error ，应该是之前您有一次提交改变了工程的目录结构导致，尝试修改关联的 CMakeLists 最终也没编起来，报了 `Unknown CMake command "add_subdirectory_ifdef"` 我在最新的 CMake 文档中未找到这个 API ，请问需要特殊的处理步骤吗？

**Comment by versaloon** [comment]
你好，最近软件目录结构改动比较多，后面会更新一下esp32的工程。不过，目前esp32并不会主力维护，因为调试并不太方便，也没有什么支持，esp32建议还是使用官方的idf。
